version: '3'
services:
    web:
        container_name: web
        restart: always
        build: ./images/web/.
        ports:
            - '8000:80'
            #- '8443:443'
        links:
            - mariadb
        volumes: 
            - ./www:/var/www/html
            - ./logs/httpd:/etc/httpd/logs
            - ./config/vhosts:/etc/httpd/vhosts
        environment:
            PHP_UPLOAD_MAX_FILESIZE: 100M
            PHP_POST_MAX_SIZE: 1024M
            PHP_MEMORY_LIMIT: 2048M
            PHP_MAX_EXECUTION_TIME: 60
    mariadb:
        container_name: mariadb
        restart: always
        image: mariadb:10.4
        ports:
            - '3306:3306'
        volumes: 
            - ./data/mariadb:/var/lib/mysql
            - ./logs/mariadb:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: app
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app